name: Run Goose Migrations

on:
  workflow_dispatch:  # вручную запускаешь
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Running migrations..."
          goose -dir migrations postgres "$DATABASE_URL" up
